#!/bin/bash

# Source app helpers
. /usr/share/yunohost/helpers


# Retrieve app id
app=$YNH_APP_INSTANCE_NAME
 
# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
 
#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
 
final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"
 
path_url=$(ynh_normalize_url_path $path_url)	# Check and normalize path
 
# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url




 
#=================================================
# CREATE A MYSQL DB
#=================================================
 
db_name=$(ynh_sanitize_dbid ffsync)
db_user="$db_name"
 
# Generate random DES key & passwor
deskey=$(ynh_string_random 24)
ynh_app_setting_set "$app" mysqlpwd "$deskey"
 
# Initialize database
ynh_mysql_setup_db "$db_user"   "$db_name" "$deskey"
# Generate random password and save
secret=$(head -c 20 /dev/urandom | sha1sum | cut -d " " -f1)
ynh_app_setting_set ffsync secret $secret

# Check depends installation
#sudo apt-get install make python-dev python-virtualenv -y

# Patch the 'source' submodule with the 'patch' directory
git submodule init
git submodule update --recursive
sudo cp -a ../patch/sources/* ../sources 

# Modify assets to take path into account
sudo find ../sources/syncserver/page/sync_files/ -type f -exec sed -i -e "s@media\/img@$path\/media\/img@g" {} \;

# Copy files to the right place
final_path=/opt/yunohost/ffsync
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/ffsync /etc/init.d/
sudo cp ../conf/ffsync.logrotate /etc/logrotate.d/ffsync
sudo touch /var/log/ffsync.log

# Set permissions to ffsync directory
sudo useradd ffsync -d $final_path
sudo chown ffsync:ffsync -R $final_path
sudo chown ffsync /var/log/ffsync.log

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path\/@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/ffsync.conf
sudo cp ../conf/syncserver.ini $final_path/syncserver.ini
sudo sed -i -e "s@ynhbaseurl@$domain$path@g" $final_path/syncserver.ini
sudo sed -i -e "s@changesecret@$secret@g" $final_path/syncserver.ini
sudo sed -i "s/yunouser/$db_user/g" $final_path/syncserver.ini
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/syncserver.ini
sudo sed -i "s/yunobase/$db_user/g" $final_path/syncserver.ini
sudo sed -i -e "s@media\/img@$path\/media\/img@g" $final_path/syncserver/page/sync_files/firefox_sync-bundle.css
sudo sed -i -e "s@media\/img@$path\/media\/img@g" $final_path/syncserver/page/sync_files/responsive-bundle.css

# Init virtualenv
cd $final_path && sudo make build && sudo ./local/bin/easy_install gunicorn

# Disable swapfile
if [ -z ${tmp_swap_file+x} ];
then
        sudo swapoff $tmp_swap_file
        sudo rm -f $tmp_swap_file
fi

# Fix permission
sudo find $final_path/ -type d -exec chmod 2755 {} \;
sudo find $final_path/ -type f -exec chmod g+r,o+r {} \;

#enable services
sudo chmod +x /etc/init.d/ffsync
sudo update-rc.d ffsync defaults
sudo service ffsync restart
sudo service ffsync restart
sudo service ffsync restart

# Reload Nginx and regenerate SSOwat conf
sudo yunohost app ssowatconf
sudo service nginx restart
sudo yunohost service add ffsync -l /var/log/ffsync.log
ynh_app_setting_set ffsync skipped_uris "/"
